-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

fib :: [Int] -> [Int]
fib all@(x:y:xs) = (x+y):all

fibUntil :: Int -> [Int] -> [Int]
fibUntil n arr
  | head arr >= n = tail arr
  | head arr < n  = fibUntil n (fib arr)

main = do
  print $ fib $ fib [2,1]
  print $ sum $ filter even $ fibUntil 4000000 [2,1]
